### PR TITLE
fix an error in unmarshal leader

### PR DESCRIPTION
**Pull request by jiaola**
Hi,

I found an error in the code that parses the leader of marc records. Please review. 

David

### CODE REVIEW

**Comment by atz** [comment]
Got a test case for that?

**Comment by jiaola** [comment]
I just wrote one. https://github.com/jiaola/marc4j/commit/e86eda3744c91eda9dfd64ddd5b00162d96c4e48

Let me know what's the easiest way to proceed. Shall I close this one and create a new pull request?

**Comment by jiaola** [comment]
@atz Just want to check with you again about this pull request.

**Comment by atz** [comment]
I would defer to @sesuncedu or @haschart on this one.

**Pull request merged**
